package entity;
// Generated 22-apr-2013 22:04:37 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NegotiationId generated by hbm2java
 */
@Embeddable
public class NegotiationId  implements java.io.Serializable {


     private int idMember;
     private int idRide;

    public NegotiationId() {
    }

    public NegotiationId(int idMember, int idRide) {
       this.idMember = idMember;
       this.idRide = idRide;
    }
   

    @Column(name="idMember", nullable=false)
    public int getIdMember() {
        return this.idMember;
    }
    
    public void setIdMember(int idMember) {
        this.idMember = idMember;
    }

    @Column(name="idRide", nullable=false)
    public int getIdRide() {
        return this.idRide;
    }
    
    public void setIdRide(int idRide) {
        this.idRide = idRide;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NegotiationId) ) return false;
		 NegotiationId castOther = ( NegotiationId ) other; 
         
		 return (this.getIdMember()==castOther.getIdMember())
 && (this.getIdRide()==castOther.getIdRide());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMember();
         result = 37 * result + this.getIdRide();
         return result;
   }   


}


