package entity;
// Generated 22-apr-2013 22:04:37 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Negotiation generated by hbm2java
 */
@Entity
@Table(name="negotiation"
    ,catalog="dryves"
)
public class Negotiation  implements java.io.Serializable {


     private NegotiationId id;
     private Ride ride;
     private Member member;
     private int acceptedDriver;
     private Integer acceptedPassenger;
     private Set<Bid> bids = new HashSet<Bid>(0);

    public Negotiation() {
    }

	
    public Negotiation(NegotiationId id, Ride ride, Member member, int acceptedDriver) {
        this.id = id;
        this.ride = ride;
        this.member = member;
        this.acceptedDriver = acceptedDriver;
    }
    public Negotiation(NegotiationId id, Ride ride, Member member, int acceptedDriver, Integer acceptedPassenger, Set<Bid> bids) {
       this.id = id;
       this.ride = ride;
       this.member = member;
       this.acceptedDriver = acceptedDriver;
       this.acceptedPassenger = acceptedPassenger;
       this.bids = bids;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idMember", column=@Column(name="idMember", nullable=false) ), 
        @AttributeOverride(name="idRide", column=@Column(name="idRide", nullable=false) ) } )
    public NegotiationId getId() {
        return this.id;
    }
    
    public void setId(NegotiationId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idRide", nullable=false, insertable=false, updatable=false)
    public Ride getRide() {
        return this.ride;
    }
    
    public void setRide(Ride ride) {
        this.ride = ride;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMember", nullable=false, insertable=false, updatable=false)
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    
    @Column(name="acceptedDriver", nullable=false)
    public int getAcceptedDriver() {
        return this.acceptedDriver;
    }
    
    public void setAcceptedDriver(int acceptedDriver) {
        this.acceptedDriver = acceptedDriver;
    }
    
    @Column(name="acceptedPassenger")
    public Integer getAcceptedPassenger() {
        return this.acceptedPassenger;
    }
    
    public void setAcceptedPassenger(Integer acceptedPassenger) {
        this.acceptedPassenger = acceptedPassenger;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="negotiation")
    public Set<Bid> getBids() {
        return this.bids;
    }
    
    public void setBids(Set<Bid> bids) {
        this.bids = bids;
    }




}


