package entity;
// Generated 22-apr-2013 22:04:37 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="dryves"
)
public class Admin  implements java.io.Serializable {


     private int idAdmin;
     private Member member;

    public Admin() {
    }

    public Admin(int idAdmin, Member member) {
       this.idAdmin = idAdmin;
       this.member = member;
    }
   
     @Id 
    
    @Column(name="idAdmin", unique=true, nullable=false)
    public int getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(int idAdmin) {
        this.idAdmin = idAdmin;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idAdmin", unique=true, nullable=false, insertable=false, updatable=false)
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }




}


