package entity;
// Generated 22-apr-2013 22:04:37 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Bid generated by hbm2java
 */
@Entity
@Table(name="bid"
    ,catalog="dryves"
)
public class Bid  implements java.io.Serializable {


     private Integer idBid;
     private Date timestamp;
     private Negotiation negotiation;
     private double amount;
     private String text;

    public Bid() {
    }

	
    public Bid(Negotiation negotiation, double amount) {
        this.negotiation = negotiation;
        this.amount = amount;
    }
    public Bid(Negotiation negotiation, double amount, String text) {
       this.negotiation = negotiation;
       this.amount = amount;
       this.text = text;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idBid", unique=true, nullable=false)
    public Integer getIdBid() {
        return this.idBid;
    }
    
    public void setIdBid(Integer idBid) {
        this.idBid = idBid;
    }
   @Temporal(TemporalType.TIMESTAMP)
    @Column(name="'timestamp'", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="idMember", referencedColumnName="idMember", nullable=false), 
        @JoinColumn(name="idRide", referencedColumnName="idRide", nullable=false) } )
    public Negotiation getNegotiation() {
        return this.negotiation;
    }
    
    public void setNegotiation(Negotiation negotiation) {
        this.negotiation = negotiation;
    }
    
    @Column(name="amount", nullable=false, precision=22, scale=0)
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
    
    @Column(name="text", length=65535)
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


