package entity;
// Generated 22-apr-2013 22:04:37 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name="message"
    ,catalog="dryves"
)
public class Message  implements java.io.Serializable {


     private Integer idMessage;
     private Member memberByIdMemberSender;
     private Member memberByIdMemberReciever;
     private String text, dateTime;

    public Message() {
    }

	
    public Message(Member memberByIdMemberSender, Member memberByIdMemberReciever) {
        this.memberByIdMemberSender = memberByIdMemberSender;
        this.memberByIdMemberReciever = memberByIdMemberReciever;
    }
    public Message(Member memberByIdMemberSender, Member memberByIdMemberReciever, String text) {
       this.memberByIdMemberSender = memberByIdMemberSender;
       this.memberByIdMemberReciever = memberByIdMemberReciever;
       this.text = text;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idMessage", unique=true, nullable=false)
    public Integer getIdMessage() {
        return this.idMessage;
    }
    
    public void setIdMessage(Integer idMessage) {
        this.idMessage = idMessage;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMemberSender", nullable=false)
    public Member getMemberByIdMemberSender() {
        return this.memberByIdMemberSender;
    }
    
    public void setMemberByIdMemberSender(Member memberByIdMemberSender) {
        this.memberByIdMemberSender = memberByIdMemberSender;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMemberReciever", nullable=false)
    public Member getMemberByIdMemberReciever() {
        return this.memberByIdMemberReciever;
    }
    
    public void setMemberByIdMemberReciever(Member memberByIdMemberReciever) {
        this.memberByIdMemberReciever = memberByIdMemberReciever;
    }
    
    @Column(name="text", length=156)
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }

    @Column(name="dateTime", nullable=false)
    public String getDateTime(){
        return this.dateTime;
    }

    public void setDateTime(String dateTime){
        this.dateTime = dateTime;
    }

}


