package entity;
// Generated 22-apr-2013 22:04:37 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rating generated by hbm2java
 */
@Entity
@Table(name="rating"
    ,catalog="dryves"
)
public class Rating  implements java.io.Serializable {


     private Integer idRating;
     private Member member;
     private int score;
     private String comment;
     private String ratingType;

    public Rating() {
    }

	
    public Rating(Member member, int score, String ratingType) {
        this.member = member;
        this.score = score;
        this.ratingType = ratingType;
    }
    public Rating(Member member, int score, String comment, String ratingType) {
       this.member = member;
       this.score = score;
       this.comment = comment;
       this.ratingType = ratingType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idRating", unique=true, nullable=false)
    public Integer getIdRating() {
        return this.idRating;
    }
    
    public void setIdRating(Integer idRating) {
        this.idRating = idRating;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMember", nullable=false)
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    
    @Column(name="score", nullable=false)
    public int getScore() {
        return this.score;
    }
    
    public void setScore(int score) {
        this.score = score;
    }
    
    @Column(name="comment", length=65535)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    
    @Column(name="ratingType", nullable=false, length=45)
    public String getRatingType() {
        return this.ratingType;
    }
    
    public void setRatingType(String ratingType) {
        this.ratingType = ratingType;
    }




}


